/**
 * Action Chain Orchestrator
 * Executes 4 parallel response lanes after CVE triage approval
 * 
 * Lane 1: Auto-containment (WAF rules, network ACLs, segmentation)
 * Lane 2: Patch orchestration (vendor commands, CI/CD, rollback)
 * Lane 3: Stakeholder alerting (Slack, email, PagerDuty)
 * Lane 4: Forensic evidence (logs, memory dumps, chain-of-custody)
 */

/**
 * Lane 1: Auto-Containment
 * Generates containment artifacts for immediate threat mitigation
 */
async function generateContainment(triageOutput) {
  const startTime = Date.now();

  try {
    // Simulate processing time
    await new Promise(resolve => setTimeout(resolve, 600));

    const cveId = triageOutput.cve_id;
    const severity = triageOutput.severity;
    const attackVector = triageOutput.attack_vector;

    // Generate WAF rule (ModSecurity format)
    const wafRule = generateWAFRule(triageOutput);

    // Generate network ACL
    const networkACL = generateNetworkACL(triageOutput);

    // Generate segmentation recommendation
    const segmentation = generateSegmentationPlan(triageOutput);

    // Calculate confidence
    const confidence = calculateContainmentConfidence(triageOutput);

    return {
      lane: 'auto-containment',
      status: 'complete',
      execution_time_ms: Date.now() - startTime,
      artifacts: {
        waf_rule: wafRule,
        network_acl: networkACL,
        segmentation_plan: segmentation,
        containment_confidence: confidence
      },
      generated_by: 'ThreatScribe + watsonx.ai',
      qa_required: true
    };

  } catch (error) {
    return {
      lane: 'auto-containment',
      status: 'error',
      execution_time_ms: Date.now() - startTime,
      error: error.message
    };
  }
}

/**
 * Generate ModSecurity WAF rule
 */
function generateWAFRule(triageOutput) {
  const cveId = triageOutput.cve_id.replace(/[^a-zA-Z0-9]/g, '_');
  const description = triageOutput.description.substring(0, 100);

  return {
    format: 'ModSecurity',
    rule: `# WAF Rule for ${triageOutput.cve_id}
# Generated by ThreatScribe AI
# Severity: ${triageOutput.severity}

SecRule REQUEST_URI|ARGS|REQUEST_BODY "@rx (?i)(exploit|payload|malicious_pattern)" \\
    "id:${Math.floor(Math.random() * 900000) + 100000},\\
    phase:2,\\
    block,\\
    t:none,t:urlDecodeUni,t:lowercase,\\
    msg:'${triageOutput.cve_id} - Potential exploitation attempt detected',\\
    logdata:'Matched Data: %{MATCHED_VAR} found within %{MATCHED_VAR_NAME}',\\
    severity:'CRITICAL',\\
    tag:'${triageOutput.cve_id}',\\
    tag:'attack-${triageOutput.mitre.tactic.toLowerCase().replace(' ', '-')}'"`,
    deployment_notes: 'Test in monitoring mode before enabling blocking. Adjust pattern based on specific exploit signatures.',
    false_positive_risk: 'Medium - Review logs for legitimate traffic patterns'
  };
}

/**
 * Generate network ACL entry
 */
function generateNetworkACL(triageOutput) {
  const isNetworkBased = triageOutput.attack_vector === 'Network';

  if (!isNetworkBased) {
    return {
      applicable: false,
      reason: `Attack vector is ${triageOutput.attack_vector}, not Network-based`
    };
  }

  return {
    applicable: true,
    iptables: `# Block suspicious traffic for ${triageOutput.cve_id}
# Add to iptables rules
iptables -A INPUT -p tcp --dport <vulnerable_port> -m state --state NEW -m recent --set --name ${triageOutput.cve_id.replace(/[^a-zA-Z0-9]/g, '_')}
iptables -A INPUT -p tcp --dport <vulnerable_port> -m state --state NEW -m recent --update --seconds 60 --hitcount 10 --name ${triageOutput.cve_id.replace(/[^a-zA-Z0-9]/g, '_')} -j DROP`,
    cloud_acl: {
      aws_security_group: {
        action: 'Deny',
        protocol: 'TCP',
        port_range: '<vulnerable_port>',
        source: '0.0.0.0/0',
        description: `Block ${triageOutput.cve_id} exploitation attempts`
      },
      azure_nsg: {
        name: `Block-${triageOutput.cve_id}`,
        priority: 100,
        direction: 'Inbound',
        access: 'Deny',
        protocol: 'TCP',
        destination_port_range: '<vulnerable_port>'
      }
    },
    deployment_notes: 'Replace <vulnerable_port> with actual service port. Test connectivity before production deployment.'
  };
}

/**
 * Generate network segmentation plan
 */
function generateSegmentationPlan(triageOutput) {
  const severity = triageOutput.severity;
  const affectedProducts = triageOutput.affected_products;

  return {
    recommendation: severity === 'CRITICAL' ? 'Immediate isolation' : 'Enhanced monitoring',
    vlans_to_isolate: affectedProducts.map(p => `VLAN for ${p.vendor} ${p.product}`),
    isolation_steps: [
      'Identify all affected systems via asset inventory',
      'Move affected systems to quarantine VLAN',
      'Apply strict ACLs between quarantine and production VLANs',
      'Enable enhanced logging on quarantine VLAN',
      'Monitor for lateral movement attempts'
    ],
    duration: severity === 'CRITICAL' ? 'Until patched and verified' : 'Until risk assessment complete',
    rollback_plan: 'Document original VLAN assignments. Restore after successful patching and IBM Bob validation.'
  };
}

/**
 * Calculate containment confidence score
 */
function calculateContainmentConfidence(triageOutput) {
  let confidence = 0.7; // Base confidence

  // Boost for network-based attacks (easier to contain)
  if (triageOutput.attack_vector === 'Network') {
    confidence += 0.15;
  }

  // Boost for high triage confidence
  if (triageOutput.triage_confidence >= 0.9) {
    confidence += 0.1;
  }

  // Reduce for complex attacks
  if (triageOutput.attack_complexity === 'High') {
    confidence -= 0.1;
  }

  return Math.min(0.95, Math.max(0.5, confidence));
}

/**
 * Lane 2: Patch Orchestration
 * Generates patching artifacts and CI/CD integration
 */
async function generatePatching(triageOutput) {
  const startTime = Date.now();

  try {
    await new Promise(resolve => setTimeout(resolve, 600));

    const patchCommand = generatePatchCommand(triageOutput);
    const verificationChecklist = generateVerificationChecklist(triageOutput);
    const cicdTrigger = generateCICDTrigger(triageOutput);
    const regressionTests = generateRegressionTests(triageOutput);
    const rollbackCommand = generateRollbackCommand(triageOutput);

    return {
      lane: 'patch-orchestration',
      status: 'complete',
      execution_time_ms: Date.now() - startTime,
      artifacts: {
        patch_command: patchCommand,
        pre_patch_checklist: verificationChecklist.pre_patch,
        post_patch_checklist: verificationChecklist.post_patch,
        cicd_trigger: cicdTrigger,
        regression_tests: regressionTests,
        rollback_command: rollbackCommand
      },
      generated_by: 'ThreatScribe + watsonx.ai',
      qa_required: true
    };

  } catch (error) {
    return {
      lane: 'patch-orchestration',
      status: 'error',
      execution_time_ms: Date.now() - startTime,
      error: error.message
    };
  }
}

/**
 * Generate vendor-specific patch command
 */
function generatePatchCommand(triageOutput) {
  const products = triageOutput.affected_products;
  const commands = {};

  for (const product of products) {
    const vendor = product.vendor.toLowerCase();
    
    if (vendor.includes('linux') || vendor.includes('ubuntu') || vendor.includes('debian')) {
      commands.debian_ubuntu = `# Update ${product.product}
sudo apt-get update
sudo apt-get install --only-upgrade ${product.product}
sudo systemctl restart ${product.product}`;
    } else if (vendor.includes('redhat') || vendor.includes('centos')) {
      commands.redhat_centos = `# Update ${product.product}
sudo yum update ${product.product}
sudo systemctl restart ${product.product}`;
    } else if (vendor.includes('windows') || vendor.includes('microsoft')) {
      commands.windows = `# Update ${product.product} (PowerShell)
# Download patch from vendor
# Install-WindowsUpdate -KBArticleID <KB_NUMBER> -AcceptAll
Restart-Service -Name "${product.product}" -Force`;
    } else {
      commands.generic = `# Generic update command for ${product.vendor} ${product.product}
# Consult vendor documentation for specific patch procedure
# Verify patch authenticity before installation`;
    }
  }

  return {
    commands: commands,
    notes: 'Always test patches in staging environment first. Verify patch authenticity using vendor signatures.',
    estimated_downtime: triageOutput.severity === 'CRITICAL' ? '5-15 minutes' : '10-30 minutes'
  };
}

/**
 * Generate verification checklist
 */
function generateVerificationChecklist(triageOutput) {
  return {
    pre_patch: [
      'Backup all affected systems',
      'Document current system state',
      'Notify stakeholders of maintenance window',
      'Prepare rollback plan',
      'Test patch in staging environment',
      'Verify patch authenticity'
    ],
    post_patch: [
      'Verify service functionality',
      'Check system logs for errors',
      'Run IBM Bob validation tests',
      'Confirm vulnerability is remediated',
      'Update asset inventory',
      'Document patch deployment'
    ]
  };
}

/**
 * Generate CI/CD pipeline trigger
 */
function generateCICDTrigger(triageOutput) {
  return {
    pipeline_recommendation: 'staging → approval → production',
    stages: {
      staging: {
        trigger: 'automatic',
        tests: ['unit', 'integration', 'ibm-bob-validation'],
        approval_required: false
      },
      approval: {
        trigger: 'manual',
        approvers: ['security-team', 'ops-team'],
        criteria: 'All IBM Bob tests passed + no regressions detected'
      },
      production: {
        trigger: 'manual',
        deployment_strategy: triageOutput.severity === 'CRITICAL' ? 'blue-green' : 'rolling',
        rollback_trigger: 'automatic on failure'
      }
    },
    example_config: {
      github_actions: `.github/workflows/security-patch.yml`,
      jenkins: `pipeline { stages { stage('Patch') { ... } } }`,
      gitlab_ci: `.gitlab-ci.yml`
    }
  };
}

/**
 * Generate IBM Bob regression test bundle
 */
function generateRegressionTests(triageOutput) {
  return {
    test_suite: `ibm-bob-${triageOutput.cve_id.toLowerCase()}`,
    tests: [
      {
        id: 'RT001',
        name: 'Verify vulnerability is patched',
        command: `curl -X POST http://localhost/vulnerable-endpoint -d "exploit_payload"`,
        expected: 'Request blocked or service not vulnerable'
      },
      {
        id: 'RT002',
        name: 'Verify service functionality',
        command: `curl -X GET http://localhost/health`,
        expected: 'HTTP 200 OK'
      },
      {
        id: 'RT003',
        name: 'Verify no regression in core features',
        command: `npm test -- --grep "core features"`,
        expected: 'All tests pass'
      }
    ],
    execution: 'Run after patch deployment, before marking as complete'
  };
}

/**
 * Generate rollback command
 */
function generateRollbackCommand(triageOutput) {
  return {
    single_command: `# Emergency rollback for ${triageOutput.cve_id}
# Restore from backup
sudo systemctl stop <service>
sudo cp /backup/<service>-pre-patch /opt/<service>
sudo systemctl start <service>
# Verify rollback
curl http://localhost/health`,
    verification: 'Check service logs and functionality after rollback',
    escalation: 'If rollback fails, contact vendor support immediately'
  };
}

/**
 * Lane 3: Stakeholder Alerting
 * Generates multi-channel notifications
 */
async function generateAlerting(triageOutput) {
  const startTime = Date.now();

  try {
    await new Promise(resolve => setTimeout(resolve, 600));

    const slackMessage = generateSlackMessage(triageOutput);
    const emailMessage = generateEmailMessage(triageOutput);
    const pagerDutyAlert = generatePagerDutyAlert(triageOutput);

    return {
      lane: 'stakeholder-alerting',
      status: 'complete',
      execution_time_ms: Date.now() - startTime,
      artifacts: {
        slack: slackMessage,
        email: emailMessage,
        pagerduty: pagerDutyAlert
      },
      generated_by: 'ThreatScribe + watsonx.ai',
      qa_required: false
    };

  } catch (error) {
    return {
      lane: 'stakeholder-alerting',
      status: 'error',
      execution_time_ms: Date.now() - startTime,
      error: error.message
    };
  }
}

/**
 * Generate Slack message
 */
function generateSlackMessage(triageOutput) {
  const emoji = triageOutput.severity === 'CRITICAL' ? '🚨' : 
                triageOutput.severity === 'HIGH' ? '⚠️' : 'ℹ️';
  
  const message = `${emoji} *${triageOutput.severity}* ${triageOutput.cve_id}: ${triageOutput.description.substring(0, 100)}...`;

  return {
    text: message,
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `${emoji} ${triageOutput.severity}: ${triageOutput.cve_id}`
        }
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*CVSS Score:*\n${triageOutput.cvss_score}` },
          { type: 'mrkdwn', text: `*Action:*\n${triageOutput.recommended_action}` }
        ]
      },
      {
        type: 'actions',
        elements: [
          {
            type: 'button',
            text: { type: 'plain_text', text: 'View Report' },
            url: 'https://threatscribe.local/reports/' + triageOutput.cve_id
          }
        ]
      }
    ],
    channel: triageOutput.severity === 'CRITICAL' ? '#security-critical' : '#security-alerts'
  };
}

/**
 * Generate executive email
 */
function generateEmailMessage(triageOutput) {
  const subject = `[${triageOutput.severity}] Security Alert: ${triageOutput.cve_id}`;
  
  const body = `A ${triageOutput.severity.toLowerCase()}-severity security vulnerability has been detected and requires immediate attention.

What happened: ${triageOutput.description}

Impact: This vulnerability affects ${triageOutput.affected_products.map(p => p.product).join(', ')} and could allow attackers to ${triageOutput.mitre.technique_name.toLowerCase()}.

Action required: ${triageOutput.recommended_action}

Timeline: ${triageOutput.severity === 'CRITICAL' ? 'Immediate action required within 24 hours' : 'Action required within 72 hours'}

The security team is already working on containment and remediation. You will receive updates as the situation progresses.

For technical details, please contact the security team.`;

  return {
    to: ['security-team@company.com', 'ciso@company.com'],
    cc: triageOutput.severity === 'CRITICAL' ? ['cto@company.com', 'ceo@company.com'] : [],
    subject: subject,
    body: body,
    priority: triageOutput.severity === 'CRITICAL' ? 'high' : 'normal'
  };
}

/**
 * Generate PagerDuty alert
 */
function generatePagerDutyAlert(triageOutput) {
  return {
    routing_key: '<your_pagerduty_integration_key>',
    event_action: 'trigger',
    payload: {
      summary: `${triageOutput.severity}: ${triageOutput.cve_id} detected`,
      severity: triageOutput.severity.toLowerCase(),
      source: 'ThreatScribe AI',
      component: triageOutput.affected_products[0]?.product || 'Unknown',
      group: 'security',
      class: 'cve',
      custom_details: {
        cve_id: triageOutput.cve_id,
        cvss_score: triageOutput.cvss_score,
        attack_vector: triageOutput.attack_vector,
        recommended_action: triageOutput.recommended_action,
        mitre_technique: triageOutput.mitre.technique_id
      }
    },
    links: [
      {
        href: 'https://threatscribe.local/reports/' + triageOutput.cve_id,
        text: 'View Full Report'
      }
    ]
  };
}

/**
 * Lane 4: Forensic Evidence Collection
 * Generates forensic collection procedures
 */
async function generateForensics(triageOutput) {
  const startTime = Date.now();

  try {
    await new Promise(resolve => setTimeout(resolve, 600));

    const logSnapshot = generateLogSnapshotCommand(triageOutput);
    const memoryDump = generateMemoryDumpProcedure(triageOutput);
    const chainOfCustody = generateChainOfCustody(triageOutput);
    const complianceNotes = generateComplianceNotes(triageOutput);

    return {
      lane: 'forensic-evidence',
      status: 'complete',
      execution_time_ms: Date.now() - startTime,
      artifacts: {
        log_snapshot: logSnapshot,
        memory_dump: memoryDump,
        chain_of_custody: chainOfCustody,
        compliance_notes: complianceNotes
      },
      generated_by: 'ThreatScribe + watsonx.ai',
      qa_required: true
    };

  } catch (error) {
    return {
      lane: 'forensic-evidence',
      status: 'error',
      execution_time_ms: Date.now() - startTime,
      error: error.message
    };
  }
}

/**
 * Generate log snapshot command
 */
function generateLogSnapshotCommand(triageOutput) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const cveId = triageOutput.cve_id.replace(/[^a-zA-Z0-9]/g, '_');

  return {
    linux: `# Collect logs for ${triageOutput.cve_id}
mkdir -p /forensics/${cveId}_${timestamp}
journalctl --since "1 hour ago" > /forensics/${cveId}_${timestamp}/system.log
cp /var/log/syslog /forensics/${cveId}_${timestamp}/
cp /var/log/auth.log /forensics/${cveId}_${timestamp}/
tar -czf /forensics/${cveId}_${timestamp}.tar.gz /forensics/${cveId}_${timestamp}/
sha256sum /forensics/${cveId}_${timestamp}.tar.gz > /forensics/${cveId}_${timestamp}.tar.gz.sha256`,
    windows: `# Collect logs for ${triageOutput.cve_id} (PowerShell)
$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$path = "C:\\Forensics\\${cveId}_$timestamp"
New-Item -ItemType Directory -Path $path
Get-EventLog -LogName Security -After (Get-Date).AddHours(-1) | Export-Csv "$path\\security.csv"
Get-EventLog -LogName System -After (Get-Date).AddHours(-1) | Export-Csv "$path\\system.csv"
Compress-Archive -Path $path -DestinationPath "$path.zip"`,
    notes: 'Collect logs immediately upon detection. Preserve original timestamps. Calculate and store hash for integrity verification.'
  };
}

/**
 * Generate memory dump procedure
 */
function generateMemoryDumpProcedure(triageOutput) {
  return {
    recommendation: triageOutput.severity === 'CRITICAL' ? 'Recommended' : 'Optional',
    linux: {
      tool: 'LiME (Linux Memory Extractor)',
      command: `sudo insmod lime.ko "path=/forensics/memory_${triageOutput.cve_id}.lime format=lime"`,
      notes: 'Requires LiME kernel module. Capture before system reboot.'
    },
    windows: {
      tool: 'DumpIt or WinPmem',
      command: `DumpIt.exe /output C:\\Forensics\\memory_${triageOutput.cve_id}.dmp`,
      notes: 'Run with administrator privileges. Large file size expected.'
    },
    trigger_conditions: [
      'Active exploitation detected',
      'Unusual process behavior',
      'Potential data exfiltration',
      'Compliance requirement'
    ]
  };
}

/**
 * Generate chain of custody entry
 */
function generateChainOfCustody(triageOutput) {
  return {
    incident_id: `INC-${triageOutput.cve_id}-${Date.now()}`,
    timestamp: new Date().toISOString(),
    action: 'Evidence collection initiated',
    actor: 'ThreatScribe AI (automated)',
    artifacts: [
      {
        type: 'log_snapshot',
        location: `/forensics/${triageOutput.cve_id}_logs.tar.gz`,
        hash_algorithm: 'SHA-256',
        hash_value: '<to_be_calculated>',
        size_bytes: '<to_be_determined>'
      },
      {
        type: 'memory_dump',
        location: `/forensics/${triageOutput.cve_id}_memory.lime`,
        hash_algorithm: 'SHA-256',
        hash_value: '<to_be_calculated>',
        size_bytes: '<to_be_determined>'
      }
    ],
    next_custodian: 'SOC Analyst',
    retention_period: 'See compliance notes',
    notes: 'All artifacts collected via automated ThreatScribe workflow. Manual verification required.'
  };
}

/**
 * Generate compliance preservation notes
 */
function generateComplianceNotes(triageOutput) {
  return {
    frameworks: {
      'SOC 2': {
        requirement: 'Retain security incident evidence for audit purposes',
        retention_period: '90 days minimum, 1 year recommended',
        storage_requirements: 'Encrypted, access-controlled, tamper-evident'
      },
      'ISO 27001': {
        requirement: 'Document security incidents and response actions',
        retention_period: 'Duration of certification + 3 years',
        storage_requirements: 'Secure storage with audit trail'
      },
      'NIST CSF': {
        requirement: 'Maintain forensic evidence for incident analysis',
        retention_period: 'As defined by organizational policy',
        storage_requirements: 'Integrity-protected, available for analysis'
      }
    },
    recommended_retention: triageOutput.severity === 'CRITICAL' ? '2 years' : '1 year',
    disposal_procedure: 'Secure deletion with certificate of destruction after retention period'
  };
}

/**
 * Execute all 4 lanes in parallel
 */
export async function executeActionChain(triageOutput, qaReport) {
  const startTime = Date.now();

  try {
    // Verify QA approval
    if (qaReport.qa_status === 'REJECTED') {
      throw new Error('Action chain blocked: CVE failed QA validation');
    }

    // Execute all lanes in parallel
    const [lane1, lane2, lane3, lane4] = await Promise.all([
      generateContainment(triageOutput),
      generatePatching(triageOutput),
      generateAlerting(triageOutput),
      generateForensics(triageOutput)
    ]);

    // Generate Sigma SIEM rule
    const sigmaRule = generateSigmaRule(triageOutput);

    // Generate IBM Bob test bundle for Sigma rule
    const sigmaTests = generateSigmaTestBundle(triageOutput);

    // Generate intel feedback
    const intelFeedback = generateIntelFeedback(triageOutput, qaReport);

    return {
      status: 'complete',
      execution_time_ms: Date.now() - startTime,
      lanes: {
        containment: lane1,
        patching: lane2,
        alerting: lane3,
        forensics: lane4
      },
      additional_artifacts: {
        sigma_rule: sigmaRule,
        sigma_tests: sigmaTests,
        intel_feedback: intelFeedback
      },
      summary: {
        total_artifacts: 20,
        qa_required_count: 3,
        ready_for_deployment: qaReport.qa_status === 'APPROVED'
      }
    };

  } catch (error) {
    return {
      status: 'error',
      execution_time_ms: Date.now() - startTime,
      error: error.message
    };
  }
}

/**
 * Generate Sigma SIEM rule
 */
function generateSigmaRule(triageOutput) {
  return {
    title: `${triageOutput.cve_id} Exploitation Attempt`,
    id: `sigma-${triageOutput.cve_id.toLowerCase()}`,
    status: 'experimental',
    description: `Detects potential exploitation attempts of ${triageOutput.cve_id}`,
    references: [`https://nvd.nist.gov/vuln/detail/${triageOutput.cve_id}`],
    tags: [
      `attack.${triageOutput.mitre.tactic.toLowerCase().replace(' ', '_')}`,
      `attack.${triageOutput.mitre.technique_id.toLowerCase()}`
    ],
    logsource: {
      category: 'network',
      product: 'firewall'
    },
    detection: {
      selection: {
        destination_port: '<vulnerable_port>',
        payload: '*exploit*pattern*'
      },
      condition: 'selection'
    },
    falsepositives: ['Legitimate traffic to affected service'],
    level: triageOutput.severity.toLowerCase()
  };
}

/**
 * Generate IBM Bob test bundle for Sigma rule
 */
function generateSigmaTestBundle(triageOutput) {
  return {
    test_suite: `sigma-validation-${triageOutput.cve_id}`,
    tests: [
      {
        id: 'ST001',
        name: 'Verify Sigma rule triggers on exploit attempt',
        input: 'Simulated exploit traffic',
        expected: 'Alert generated'
      },
      {
        id: 'ST002',
        name: 'Verify no false positives on legitimate traffic',
        input: 'Normal service traffic',
        expected: 'No alert'
      }
    ]
  };
}

/**
 * Generate intel feedback entry
 */
function generateIntelFeedback(triageOutput, qaReport) {
  return {
    cve_id: triageOutput.cve_id,
    severity: triageOutput.severity,
    mitre_mapping: triageOutput.mitre,
    obfuscation_detected: triageOutput.typo_flags.length > 0,
    qa_status: qaReport.qa_status,
    lessons_learned: qaReport.regression_notes,
    timestamp: new Date().toISOString(),
    feed_back_to: 'CVE knowledge base for improved future detection'
  };
}

export default {
  executeActionChain,
  generateContainment,
  generatePatching,
  generateAlerting,
  generateForensics
};

// Made with Bob
